; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32be -mattr=+zbb -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV32BE-ZBB
; RUN: llc -mtriple=riscv64be -mattr=+zbb -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV64BE-ZBB
; RUN: llc -mtriple=riscv32be -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV32BE
; RUN: llc -mtriple=riscv64be -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV64BE

; Test byte swap operations on big-endian RISC-V

declare i16 @llvm.bswap.i16(i16)
declare i32 @llvm.bswap.i32(i32)
declare i64 @llvm.bswap.i64(i64)

define i16 @test_bswap_i16(i16 %a) {
; RV32BE-ZBB-LABEL: test_bswap_i16:
; RV32BE-ZBB:       # %bb.0:
; RV32BE-ZBB-NEXT:    rev8 a0, a0
; RV32BE-ZBB-NEXT:    srli a0, a0, 16
; RV32BE-ZBB-NEXT:    ret
;
; RV64BE-ZBB-LABEL: test_bswap_i16:
; RV64BE-ZBB:       # %bb.0:
; RV64BE-ZBB-NEXT:    rev8 a0, a0
; RV64BE-ZBB-NEXT:    srli a0, a0, 48
; RV64BE-ZBB-NEXT:    ret
;
; RV32BE-LABEL: test_bswap_i16:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    slli a1, a0, 8
; RV32BE-NEXT:    slli a0, a0, 16
; RV32BE-NEXT:    srli a0, a0, 24
; RV32BE-NEXT:    or a0, a1, a0
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: test_bswap_i16:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    slli a1, a0, 8
; RV64BE-NEXT:    slli a0, a0, 48
; RV64BE-NEXT:    srli a0, a0, 56
; RV64BE-NEXT:    or a0, a1, a0
; RV64BE-NEXT:    ret
  %1 = call i16 @llvm.bswap.i16(i16 %a)
  ret i16 %1
}

define i32 @test_bswap_i32(i32 %a) {
; RV32BE-ZBB-LABEL: test_bswap_i32:
; RV32BE-ZBB:       # %bb.0:
; RV32BE-ZBB-NEXT:    rev8 a0, a0
; RV32BE-ZBB-NEXT:    ret
;
; RV64BE-ZBB-LABEL: test_bswap_i32:
; RV64BE-ZBB:       # %bb.0:
; RV64BE-ZBB-NEXT:    rev8 a0, a0
; RV64BE-ZBB-NEXT:    srli a0, a0, 32
; RV64BE-ZBB-NEXT:    ret
;
; RV32BE-LABEL: test_bswap_i32:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    srli a1, a0, 8
; RV32BE-NEXT:    lui a2, 16
; RV32BE-NEXT:    srli a3, a0, 24
; RV32BE-NEXT:    addi a2, a2, -256
; RV32BE-NEXT:    and a1, a1, a2
; RV32BE-NEXT:    and a2, a0, a2
; RV32BE-NEXT:    or a1, a1, a3
; RV32BE-NEXT:    slli a2, a2, 8
; RV32BE-NEXT:    slli a0, a0, 24
; RV32BE-NEXT:    or a0, a0, a2
; RV32BE-NEXT:    or a0, a0, a1
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: test_bswap_i32:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    srli a1, a0, 8
; RV64BE-NEXT:    lui a2, 16
; RV64BE-NEXT:    srliw a3, a0, 24
; RV64BE-NEXT:    addi a2, a2, -256
; RV64BE-NEXT:    and a1, a1, a2
; RV64BE-NEXT:    and a2, a0, a2
; RV64BE-NEXT:    or a1, a1, a3
; RV64BE-NEXT:    slli a2, a2, 8
; RV64BE-NEXT:    slliw a0, a0, 24
; RV64BE-NEXT:    or a0, a0, a2
; RV64BE-NEXT:    or a0, a0, a1
; RV64BE-NEXT:    ret
  %1 = call i32 @llvm.bswap.i32(i32 %a)
  ret i32 %1
}

define i64 @test_bswap_i64(i64 %a) {
; RV32BE-ZBB-LABEL: test_bswap_i64:
; RV32BE-ZBB:       # %bb.0:
; RV32BE-ZBB-NEXT:    rev8 a2, a1
; RV32BE-ZBB-NEXT:    rev8 a1, a0
; RV32BE-ZBB-NEXT:    mv a0, a2
; RV32BE-ZBB-NEXT:    ret
;
; RV64BE-ZBB-LABEL: test_bswap_i64:
; RV64BE-ZBB:       # %bb.0:
; RV64BE-ZBB-NEXT:    rev8 a0, a0
; RV64BE-ZBB-NEXT:    ret
;
; RV32BE-LABEL: test_bswap_i64:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    srli a2, a1, 8
; RV32BE-NEXT:    lui a3, 16
; RV32BE-NEXT:    srli a4, a1, 24
; RV32BE-NEXT:    srli a5, a0, 8
; RV32BE-NEXT:    addi a3, a3, -256
; RV32BE-NEXT:    and a2, a2, a3
; RV32BE-NEXT:    or a2, a2, a4
; RV32BE-NEXT:    srli a4, a0, 24
; RV32BE-NEXT:    and a5, a5, a3
; RV32BE-NEXT:    or a4, a5, a4
; RV32BE-NEXT:    slli a5, a1, 24
; RV32BE-NEXT:    and a1, a1, a3
; RV32BE-NEXT:    slli a1, a1, 8
; RV32BE-NEXT:    or a1, a5, a1
; RV32BE-NEXT:    and a3, a0, a3
; RV32BE-NEXT:    slli a0, a0, 24
; RV32BE-NEXT:    slli a3, a3, 8
; RV32BE-NEXT:    or a3, a0, a3
; RV32BE-NEXT:    or a0, a1, a2
; RV32BE-NEXT:    or a1, a3, a4
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: test_bswap_i64:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    srli a1, a0, 40
; RV64BE-NEXT:    lui a2, 16
; RV64BE-NEXT:    srli a3, a0, 56
; RV64BE-NEXT:    srli a4, a0, 24
; RV64BE-NEXT:    lui a5, 4080
; RV64BE-NEXT:    addi a2, a2, -256
; RV64BE-NEXT:    and a1, a1, a2
; RV64BE-NEXT:    or a1, a1, a3
; RV64BE-NEXT:    srli a3, a0, 8
; RV64BE-NEXT:    and a4, a4, a5
; RV64BE-NEXT:    srliw a3, a3, 24
; RV64BE-NEXT:    slli a3, a3, 24
; RV64BE-NEXT:    or a3, a3, a4
; RV64BE-NEXT:    srliw a4, a0, 24
; RV64BE-NEXT:    and a5, a0, a5
; RV64BE-NEXT:    and a2, a0, a2
; RV64BE-NEXT:    slli a0, a0, 56
; RV64BE-NEXT:    slli a4, a4, 32
; RV64BE-NEXT:    slli a5, a5, 24
; RV64BE-NEXT:    or a4, a5, a4
; RV64BE-NEXT:    slli a2, a2, 40
; RV64BE-NEXT:    or a1, a3, a1
; RV64BE-NEXT:    or a0, a0, a2
; RV64BE-NEXT:    or a0, a0, a4
; RV64BE-NEXT:    or a0, a0, a1
; RV64BE-NEXT:    ret
  %1 = call i64 @llvm.bswap.i64(i64 %a)
  ret i64 %1
}
