; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32be -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV32BE
; RUN: llc -mtriple=riscv64be -verify-machineinstrs < %s | FileCheck %s --check-prefix=RV64BE

; Test basic load/store operations on big-endian RISC-V

define i32 @load_i32(ptr %p) {
; RV32BE-LABEL: load_i32:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    lw a0, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: load_i32:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    lw a0, 0(a0)
; RV64BE-NEXT:    ret
  %v = load i32, ptr %p
  ret i32 %v
}

define void @store_i32(ptr %p, i32 %v) {
; RV32BE-LABEL: store_i32:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    sw a1, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: store_i32:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    sw a1, 0(a0)
; RV64BE-NEXT:    ret
  store i32 %v, ptr %p
  ret void
}

define i16 @load_i16(ptr %p) {
; RV32BE-LABEL: load_i16:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    lh a0, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: load_i16:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    lh a0, 0(a0)
; RV64BE-NEXT:    ret
  %v = load i16, ptr %p
  ret i16 %v
}

define void @store_i16(ptr %p, i16 %v) {
; RV32BE-LABEL: store_i16:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    sh a1, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: store_i16:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    sh a1, 0(a0)
; RV64BE-NEXT:    ret
  store i16 %v, ptr %p
  ret void
}

define i8 @load_i8(ptr %p) {
; RV32BE-LABEL: load_i8:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    lbu a0, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: load_i8:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    lbu a0, 0(a0)
; RV64BE-NEXT:    ret
  %v = load i8, ptr %p
  ret i8 %v
}

define void @store_i8(ptr %p, i8 %v) {
; RV32BE-LABEL: store_i8:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    sb a1, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: store_i8:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    sb a1, 0(a0)
; RV64BE-NEXT:    ret
  store i8 %v, ptr %p
  ret void
}

define i64 @load_i64(ptr %p) {
; RV32BE-LABEL: load_i64:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    lw a2, 0(a0)
; RV32BE-NEXT:    lw a1, 4(a0)
; RV32BE-NEXT:    mv a0, a2
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: load_i64:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    ld a0, 0(a0)
; RV64BE-NEXT:    ret
  %v = load i64, ptr %p
  ret i64 %v
}

define void @store_i64(ptr %p, i64 %v) {
; RV32BE-LABEL: store_i64:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    sw a1, 0(a0)
; RV32BE-NEXT:    sw a2, 4(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: store_i64:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    sd a1, 0(a0)
; RV64BE-NEXT:    ret
  store i64 %v, ptr %p
  ret void
}

; Test float/double loads and stores
define float @load_float(ptr %p) {
; RV32BE-LABEL: load_float:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    lw a0, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: load_float:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    lw a0, 0(a0)
; RV64BE-NEXT:    ret
  %v = load float, ptr %p
  ret float %v
}

define void @store_float(ptr %p, float %v) {
; RV32BE-LABEL: store_float:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    sw a1, 0(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: store_float:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    sw a1, 0(a0)
; RV64BE-NEXT:    ret
  store float %v, ptr %p
  ret void
}

define double @load_double(ptr %p) {
; RV32BE-LABEL: load_double:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    lw a2, 0(a0)
; RV32BE-NEXT:    lw a1, 4(a0)
; RV32BE-NEXT:    mv a0, a2
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: load_double:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    ld a0, 0(a0)
; RV64BE-NEXT:    ret
  %v = load double, ptr %p
  ret double %v
}

define void @store_double(ptr %p, double %v) {
; RV32BE-LABEL: store_double:
; RV32BE:       # %bb.0:
; RV32BE-NEXT:    sw a1, 0(a0)
; RV32BE-NEXT:    sw a2, 4(a0)
; RV32BE-NEXT:    ret
;
; RV64BE-LABEL: store_double:
; RV64BE:       # %bb.0:
; RV64BE-NEXT:    sd a1, 0(a0)
; RV64BE-NEXT:    ret
  store double %v, ptr %p
  ret void
}
